# Generated by Django 4.0.2 on 2022-05-09 12:59

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='photo', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.FileField(blank=True, null=True, upload_to=account.models.file_dir_path, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceCategories',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True, serialize=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
                ('categories', models.ManyToManyField(related_name='choicecat', to='service.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Категория Лаборанта',
                'verbose_name_plural': 'Категории Лаборантов',
            },
        ),
    ]
