# Generated by Django 4.0.2 on 2022-05-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True, serialize=False)),
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('secondname', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('p_id', models.IntegerField(blank=True, null=True)),
                ('firstname', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('birth', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=7)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('progress', 'progress'), ('finished', 'finished')], default='pending', max_length=24)),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.doctor')),
            ],
        ),
    ]
