# Generated by Django 4.0.2 on 2022-05-09 12:56

from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True, serialize=False)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('items_count', models.IntegerField(default=0, verbose_name='Количество услуг')),
                ('is_continuous', models.BooleanField(choices=[(False, 'Нет'), (True, 'Да')], default=False, null=True, verbose_name='Для этой категории CRM будет генерировать файлы?')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('norm', models.TextField(blank=True, null=True, verbose_name='Норма')),
                ('file', models.FileField(blank=True, null=True, upload_to=service.models.file_dir_path, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True, serialize=False)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Услуга')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('fee', models.IntegerField(verbose_name='Гонорар в %')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='service.category', verbose_name='Категория')),
                ('parameters', models.ManyToManyField(blank=True, related_name='service_parameters', to='service.Parameters', verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
