# Generated by Django 4.0.2 on 2022-05-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('res', models.TextField(blank=True, null=True)),
                ('param_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.parameters')),
            ],
        ),
        migrations.CreateModel(
            name='PId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('p_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('progress', 'progress'), ('finished', 'finished')], default='pending', max_length=10)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.patient')),
                ('result', models.ManyToManyField(to='order.ParamResult')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.services')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('p_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('progress', 'progress'), ('finished', 'finished')], default='pending', max_length=30)),
                ('cost', models.IntegerField(null=True)),
                ('file', models.URLField(blank=True, null=True)),
                ('result_file', models.URLField(blank=True, null=True)),
                ('p_file', models.URLField(blank=True, null=True)),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpatient', to='client.patient')),
                ('results', models.ManyToManyField(blank=True, to='order.Result')),
                ('services', models.ManyToManyField(related_name='orderservice', to='service.Services')),
            ],
        ),
    ]
